baseURL = "https://yana-gestion.fr"
languageCode = 'fr-FR'
title = 'Yana Gestion'
theme = "Showcase"
enableRobotsTXT = true
canonifyURLs = true

# Paramètres SEO
[params]
description = ""
author = "Anne-Laure Pompui"

[params.social]
  opengraph = true
  twitter_cards = true

# Formats de sortie
[outputs]
  home = ["HTML"]

# Paramètres de performance
minify = true
ignoreCache = true

# Configuration des services de minification d'images et d'assets
[imaging]
  quality = 75

[asset]
  minify = true
  fingerprint = true
  enable = true
