backend:
  name: github
  branch: main
  repo: "tmiia/yanagestion"
  base_url: "https://delicate-fog-f391.telusma-nehemia.workers.dev/"
  auth_endpoint: "/auth"

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projets"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "text", required: true }
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: "Lien", name: "link", widget: "string", required: true, hint: "URL valide (incluant http:// ou https://)" }
      - { label: "Date de création", name: "date", widget: "datetime", default: "{{date}}" }
      - { label: "Tags", name: "tags", widget: "list", required: false, hint: "Liste des tags pour le projet" }
